openapi: 3.0.3
info:
  title: CLI Add Vulnerability API
  version: 1.0.0
  description: Backend endpoint for CLI vulnerability addition

servers:
  - url: http://localhost:8080
    description: Local development

paths:
  /api/vulnerabilities/cli-add:
    post:
      summary: Add or update a vulnerability via CLI
      description: |
        Creates a new vulnerability record for the specified hostname.
        - If hostname doesn't exist, creates the asset first
        - If CVE already exists for the asset, updates the existing record (upsert)
        - Requires authentication with ADMIN or VULN role
      operationId: addVulnerabilityFromCli
      tags:
        - Vulnerabilities
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddVulnerabilityRequest'
            examples:
              newVulnerability:
                summary: Add new vulnerability to existing asset
                value:
                  hostname: "webserver01"
                  cve: "CVE-2024-1234"
                  criticality: "HIGH"
                  daysOpen: 30
              withAutoCreate:
                summary: Add vulnerability with auto-created asset
                value:
                  hostname: "newserver99"
                  cve: "CVE-2023-5678"
                  criticality: "CRITICAL"
                  daysOpen: 15
      responses:
        '200':
          description: Vulnerability added or updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddVulnerabilityResponse'
              examples:
                created:
                  summary: New vulnerability created
                  value:
                    success: true
                    message: "Vulnerability CVE-2024-1234 added to asset webserver01"
                    assetName: "webserver01"
                    assetCreated: false
                    vulnerabilityId: "CVE-2024-1234"
                    operation: "CREATED"
                updated:
                  summary: Existing vulnerability updated
                  value:
                    success: true
                    message: "Vulnerability CVE-2024-1234 updated on asset webserver01"
                    assetName: "webserver01"
                    assetCreated: false
                    vulnerabilityId: "CVE-2024-1234"
                    operation: "UPDATED"
                withAssetCreated:
                  summary: Asset auto-created
                  value:
                    success: true
                    message: "Asset newserver99 created. Vulnerability CVE-2023-5678 added."
                    assetName: "newserver99"
                    assetCreated: true
                    vulnerabilityId: "CVE-2023-5678"
                    operation: "CREATED"
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                invalidCriticality:
                  summary: Invalid criticality value
                  value:
                    error: "Validation failed"
                    message: "Criticality must be CRITICAL, HIGH, MEDIUM, or LOW"
                missingHostname:
                  summary: Missing required field
                  value:
                    error: "Validation failed"
                    message: "Hostname is required"
        '401':
          description: Authentication required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Unauthorized"
                message: "Authentication required"
        '403':
          description: Insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Forbidden"
                message: "ADMIN or VULN role required"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AddVulnerabilityRequest:
      type: object
      required:
        - hostname
        - cve
        - criticality
      properties:
        hostname:
          type: string
          description: Target asset hostname (case-insensitive lookup)
          example: "webserver01"
          minLength: 1
          maxLength: 255
        cve:
          type: string
          description: CVE identifier or custom vulnerability ID
          example: "CVE-2024-1234"
          minLength: 1
          maxLength: 255
        criticality:
          type: string
          description: Severity level
          enum:
            - CRITICAL
            - HIGH
            - MEDIUM
            - LOW
          example: "HIGH"
        daysOpen:
          type: integer
          description: Number of days the vulnerability has been open (default 0)
          minimum: 0
          default: 0
          example: 30

    AddVulnerabilityResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Whether the operation succeeded
        message:
          type: string
          description: Human-readable result message
        assetName:
          type: string
          description: Name of the asset (existing or newly created)
        assetCreated:
          type: boolean
          description: True if asset was auto-created
        vulnerabilityId:
          type: string
          description: CVE identifier of the vulnerability
        operation:
          type: string
          enum:
            - CREATED
            - UPDATED
          description: Whether vulnerability was created or updated

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error type
        message:
          type: string
          description: Error details
