openapi: 3.0.3
info:
  title: Delete Vulnerability Exception API
  description: Delete a vulnerability exception
  version: 1.0.0
  contact:
    name: secman API

paths:
  /api/vulnerability-exceptions/{id}:
    delete:
      summary: Delete vulnerability exception
      description: |
        Permanently delete a vulnerability exception by ID.
        Requires ADMIN or VULN role.
      operationId: deleteVulnerabilityException
      tags:
        - Vulnerability Management
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Exception ID to delete
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Exception deleted successfully (no content)
        '401':
          description: Unauthorized - No valid JWT token provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - User does not have ADMIN or VULN role
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not found - Exception with specified ID does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
          example: "Exception not found with ID: 123"
        details:
          type: string
          nullable: true
          description: Additional error details
