openapi: 3.0.3
info:
  title: Get Vulnerability Exceptions API
  description: Retrieve all vulnerability exceptions with optional filtering
  version: 1.0.0
  contact:
    name: secman API

paths:
  /api/vulnerability-exceptions:
    get:
      summary: Get all vulnerability exceptions
      description: |
        Retrieve all vulnerability exceptions, including both active and expired exceptions.
        Requires ADMIN or VULN role.
      operationId: getVulnerabilityExceptions
      tags:
        - Vulnerability Management
      security:
        - bearerAuth: []
      parameters:
        - name: activeOnly
          in: query
          description: Filter to only active (non-expired) exceptions
          required: false
          schema:
            type: boolean
            default: false
        - name: type
          in: query
          description: Filter by exception type
          required: false
          schema:
            type: string
            enum: [IP, PRODUCT]
      responses:
        '200':
          description: Successfully retrieved vulnerability exceptions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/VulnerabilityExceptionDto'
        '401':
          description: Unauthorized - No valid JWT token provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - User does not have ADMIN or VULN role
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    VulnerabilityExceptionDto:
      type: object
      required:
        - id
        - exceptionType
        - targetValue
        - reason
        - createdBy
        - createdAt
        - isActive
      properties:
        id:
          type: integer
          format: int64
          description: Exception record ID
          example: 7
        exceptionType:
          type: string
          enum: [IP, PRODUCT]
          description: Type of exception (IP-based or product-based)
          example: "PRODUCT"
        targetValue:
          type: string
          maxLength: 512
          description: IP address (for IP type) or product name pattern (for PRODUCT type)
          example: "OpenSSH 7.4"
        expirationDate:
          type: string
          format: date-time
          nullable: true
          description: When exception expires (ISO 8601 format). Null means permanent exception.
          example: "2025-12-31T23:59:59"
        reason:
          type: string
          maxLength: 1024
          description: Justification for the exception
          example: "Compensating controls in place - WAF blocks this attack vector"
        createdBy:
          type: string
          maxLength: 255
          description: Username who created the exception
          example: "john.doe"
        createdAt:
          type: string
          format: date-time
          description: When exception was created (ISO 8601 format)
          example: "2025-10-01T10:15:00"
        isActive:
          type: boolean
          description: Whether exception is currently active (not expired)
          example: true
        affectedVulnerabilityCount:
          type: integer
          nullable: true
          description: Number of current vulnerabilities covered by this exception (optional)
          example: 3

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
          example: "Forbidden: User does not have required role"
        details:
          type: string
          nullable: true
          description: Additional error details
          example: "Required role: ADMIN or VULN"
