openapi: 3.0.3
info:
  title: Update Vulnerability Exception API
  description: Update an existing vulnerability exception
  version: 1.0.0
  contact:
    name: secman API

paths:
  /api/vulnerability-exceptions/{id}:
    put:
      summary: Update vulnerability exception
      description: |
        Update all fields of an existing vulnerability exception.
        Requires ADMIN or VULN role.
      operationId: updateVulnerabilityException
      tags:
        - Vulnerability Management
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Exception ID to update
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateVulnerabilityExceptionRequest'
      responses:
        '200':
          description: Exception updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VulnerabilityExceptionDto'
        '400':
          description: Bad request - Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - No valid JWT token provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - User does not have ADMIN or VULN role
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not found - Exception with specified ID does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UpdateVulnerabilityExceptionRequest:
      type: object
      required:
        - exceptionType
        - targetValue
        - reason
      properties:
        exceptionType:
          type: string
          enum: [IP, PRODUCT]
          description: Type of exception
          example: "IP"
        targetValue:
          type: string
          maxLength: 512
          description: IP address or product name pattern
          example: "192.168.1.50"
        expirationDate:
          type: string
          format: date-time
          nullable: true
          description: When exception expires (ISO 8601 format). Null for permanent exception.
          example: "2026-06-30T23:59:59"
        reason:
          type: string
          minLength: 1
          maxLength: 1024
          description: Justification for the exception
          example: "Test system - vulnerabilities accepted until decommissioning"

    VulnerabilityExceptionDto:
      type: object
      required:
        - id
        - exceptionType
        - targetValue
        - reason
        - createdBy
        - createdAt
        - isActive
      properties:
        id:
          type: integer
          format: int64
          description: Exception record ID
        exceptionType:
          type: string
          enum: [IP, PRODUCT]
          description: Type of exception
        targetValue:
          type: string
          maxLength: 512
          description: IP address or product name pattern
        expirationDate:
          type: string
          format: date-time
          nullable: true
          description: When exception expires (ISO 8601 format)
        reason:
          type: string
          maxLength: 1024
          description: Justification for the exception
        createdBy:
          type: string
          maxLength: 255
          description: Username who created the exception (unchanged on update)
        createdAt:
          type: string
          format: date-time
          description: When exception was created (unchanged on update)
        isActive:
          type: boolean
          description: Whether exception is currently active

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message
        details:
          type: string
          nullable: true
          description: Additional error details
