openapi: 3.0.3
info:
  title: Asset Management API - Domain Field
  version: 1.1.0
  description: |
    Asset Management endpoints with Active Directory domain field support.

    **Feature**: 043-crowdstrike-domain-import
    **Changes**: Documents existing `adDomain` field (from Feature 042) now populated by CrowdStrike import

servers:
  - url: http://localhost:8080/api
    description: Local development server

paths:
  /assets:
    get:
      summary: List all assets with domain information
      description: |
        Returns paginated list of assets. Each asset includes `adDomain` field when available.

        **Note**: `adDomain` field added in Feature 042, now populated automatically during
        CrowdStrike import (Feature 043).

      tags:
        - Asset Management
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            default: 20

      responses:
        '200':
          description: List of assets
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/AssetDto'
                  totalElements:
                    type: integer
                  totalPages:
                    type: integer

  /assets/{id}:
    get:
      summary: Get asset by ID
      tags:
        - Asset Management
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer

      responses:
        '200':
          description: Asset details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetDto'

    put:
      summary: Update asset (including domain field)
      description: |
        Updates asset details. The `adDomain` field can be manually edited by ADMIN users.

        **Validation**: Domain must match pattern `^[a-zA-Z0-9.-]+$` and not start/end with dots.

      tags:
        - Asset Management
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssetUpdateRequest'

      responses:
        '200':
          description: Asset updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssetDto'

        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Validation failed"
                message: "Request contains 1 validation error(s)"
                violations:
                  - "adDomain: Domain must contain only letters, numbers, dots, and hyphens (value: cont@so)"

        '403':
          description: Forbidden - user lacks ADMIN role

        '404':
          description: Asset not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AssetDto:
      type: object
      required:
        - id
        - name
        - type
        - owner
      properties:
        id:
          type: integer
          description: Asset unique identifier
          example: 42
        name:
          type: string
          description: Asset hostname or identifier
          example: web-server-01
        type:
          type: string
          description: Asset type (server, workstation, network device)
          example: server
        owner:
          type: string
          description: Asset owner username
          example: john.doe
        ip:
          type: string
          description: IP address
          example: 10.0.1.5
          nullable: true
        groups:
          type: string
          description: Comma-separated workgroup names
          example: "Production,WebServers"
          nullable: true
        cloudAccountId:
          type: string
          description: AWS account ID (12 digits)
          pattern: '^\d{12}$'
          example: "123456789012"
          nullable: true
        cloudInstanceId:
          type: string
          description: Cloud instance identifier
          example: "i-0abc123def456"
          nullable: true
        adDomain:
          type: string
          description: |
            **Feature 042/043**: Active Directory domain name.
            Automatically populated during CrowdStrike import.
            Can be manually edited by ADMIN users.
            Normalized to lowercase in database, displayed as-is.
          pattern: '^[a-zA-Z0-9.-]+$'
          example: "contoso"
          nullable: true
        osVersion:
          type: string
          description: Operating system version
          example: "Ubuntu 20.04.6 LTS"
          nullable: true
        lastSeen:
          type: string
          format: date-time
          description: Last time asset was seen/scanned
          example: "2024-03-15T14:23:45Z"
          nullable: true
        createdAt:
          type: string
          format: date-time
          description: Asset creation timestamp
          example: "2024-01-10T09:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
          example: "2024-03-15T14:23:45Z"

    AssetUpdateRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 255
        type:
          type: string
          enum: [server, workstation, network_device, other]
        owner:
          type: string
          minLength: 1
          maxLength: 255
        ip:
          type: string
          pattern: '^(\d{1,3}\.){3}\d{1,3}$'
          nullable: true
        groups:
          type: string
          nullable: true
        cloudAccountId:
          type: string
          pattern: '^\d{12}$'
          nullable: true
        cloudInstanceId:
          type: string
          nullable: true
        adDomain:
          type: string
          description: |
            Active Directory domain name.
            **Validation**:
            - Pattern: Only alphanumeric, dots, hyphens
            - Cannot start or end with dot
            - Cannot contain spaces
            - Max length: 255 characters
            - Normalized to lowercase on save
          pattern: '^[a-zA-Z0-9.-]+$'
          maxLength: 255
          nullable: true
          example: "contoso"
        osVersion:
          type: string
          nullable: true

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          example: "Validation failed"
        message:
          type: string
          example: "Request contains 1 validation error(s)"
        violations:
          type: array
          items:
            type: string
          example:
            - "adDomain: Domain must contain only letters, numbers, dots, and hyphens"
