openapi: 3.0.3
info:
  title: OIDC Default Roles - OAuth Callback Enhancement
  description: |
    Modified behavior for OAuth callback endpoint to automatically assign USER and VULN roles
    to newly created users during OIDC auto-provisioning.

    **Feature**: 046-oidc-default-roles
    **Builds on**: Feature 041 (Identity Provider OIDC/SAML)
    **Backward Compatibility**: Fully compatible - no breaking changes to API contract
  version: 1.1.0

paths:
  /oauth/callback:
    get:
      summary: OAuth 2.0 / OIDC Callback Handler
      description: |
        Handles OAuth callback after successful authentication with identity provider.

        **Modified Behavior (Feature 046)**:
        - New users created via auto-provisioning now receive default roles: USER, VULN
        - Existing users: roles unchanged (no modification on re-login)
        - Transaction atomicity: user creation + role assignment or full rollback
        - Audit logging: role assignment events logged to security.audit
        - Admin notifications: async email sent to all ADMIN role users

        **Existing Behavior (Feature 041)**:
        - Token exchange with identity provider
        - User info retrieval from OIDC userInfo endpoint
        - Auto-provisioning check (identityProvider.autoProvision must be true)
        - Session creation with JWT token
      operationId: handleOAuthCallback
      tags:
        - Authentication
      security: [] # Public endpoint (authentication happens via OAuth flow)
      parameters:
        - name: code
          in: query
          required: true
          description: Authorization code from identity provider
          schema:
            type: string
            example: "SplxlOBeZQQYbYS6WxSbIA"
        - name: state
          in: query
          required: true
          description: State parameter for CSRF protection (contains identity provider ID)
          schema:
            type: string
            example: "provider-123-random-state"
      responses:
        '302':
          description: |
            Successful authentication. Redirects to frontend with session token.

            **For new users (auto-provisioned)**:
            - User entity created with username, email, passwordHash=null
            - Roles assigned: ["USER", "VULN"]
            - Audit log entry created (timestamp, user_id, roles, identity_provider)
            - Admin notification email sent asynchronously (best-effort)

            **For existing users**:
            - User entity retrieved from database
            - Roles unchanged (preserves any admin customizations)
            - No audit log entry (not a new user creation)
            - No admin notification
          headers:
            Location:
              description: Redirect URL to frontend application
              schema:
                type: string
                example: "https://secman.example.com/?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
            Set-Cookie:
              description: Session cookie (optional, depends on configuration)
              schema:
                type: string
        '400':
          description: Bad Request - Invalid code or state parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: 400
                error: "Bad Request"
                message: "Invalid state parameter"
                timestamp: "2025-11-14T10:30:00Z"
        '401':
          description: |
            Unauthorized - Authentication failed or auto-provisioning disabled

            **Scenarios**:
            - Identity provider returned error
            - Token exchange failed
            - State validation failed (CSRF)
            - Auto-provisioning disabled and user does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: 401
                error: "Unauthorized"
                message: "Auto-provisioning is disabled for this identity provider"
                timestamp: "2025-11-14T10:30:00Z"
        '500':
          description: |
            Internal Server Error - Database failure or unexpected error

            **Transaction Rollback Scenarios** (Feature 046):
            - Database constraint violation (duplicate email - should not occur)
            - Role assignment failure
            - Transaction timeout
            **Result**: User creation rolled back completely (no orphaned users)

            **Note**: Email notification failures do NOT trigger 500 (logged only)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: 500
                error: "Internal Server Error"
                message: "Failed to create user account"
                timestamp: "2025-11-14T10:30:00Z"

components:
  schemas:
    ErrorResponse:
      type: object
      required:
        - status
        - error
        - message
        - timestamp
      properties:
        status:
          type: integer
          description: HTTP status code
          example: 401
        error:
          type: string
          description: Error type (HTTP status text)
          example: "Unauthorized"
        message:
          type: string
          description: Human-readable error message
          example: "Auto-provisioning is disabled"
        timestamp:
          type: string
          format: date-time
          description: ISO 8601 timestamp of error
          example: "2025-11-14T10:30:00Z"
        path:
          type: string
          description: Request path (optional)
          example: "/oauth/callback"

    # User entity returned internally (not in HTTP response, but documented for reference)
    User:
      type: object
      description: |
        Internal User entity (not returned directly by OAuth callback, but used in session token)
      required:
        - id
        - username
        - email
        - roles
      properties:
        id:
          type: integer
          format: int64
          description: Unique user identifier
          example: 42
        username:
          type: string
          description: User login name (derived from email for OIDC users)
          example: "john.doe"
        email:
          type: string
          format: email
          description: User email address (from OIDC userInfo)
          example: "john.doe@example.com"
        passwordHash:
          type: string
          nullable: true
          description: Bcrypt hash (null for OIDC users)
          example: null
        roles:
          type: array
          items:
            type: string
            enum: [USER, ADMIN, VULN, RELEASE_MANAGER, SECCHAMPION]
          description: |
            User roles for RBAC

            **Default for new OIDC users (Feature 046)**: ["USER", "VULN"]
          example: ["USER", "VULN"]
        createdAt:
          type: string
          format: date-time
          description: User creation timestamp
          example: "2025-11-14T10:30:00Z"

# Audit Log Format (not an API, but documented for reference)
# security.audit log entries follow this JSON structure:
#
# {
#   "timestamp": "2025-11-14T10:30:00.123Z",
#   "level": "INFO",
#   "logger": "security.audit",
#   "event": "role_assignment",
#   "user_id": 42,
#   "username": "john.doe",
#   "email": "john.doe@example.com",
#   "roles": "USER,VULN",
#   "identity_provider": "Google Workspace",
#   "message": "OIDC user created with default roles"
# }

# Email Notification Format (not an API, but documented for reference)
# Admin notification email sent to all users with ADMIN role:
#
# To: admin@example.com
# Subject: New OIDC User Created
# Template: admin-new-user.html
# Variables:
#   - user.username: "john.doe"
#   - user.email: "john.doe@example.com"
#   - user.roles: ["USER", "VULN"]
#   - idp.name: "Google Workspace"
#   - timestamp: "2025-11-14 10:30:00 UTC"
