openapi: 3.0.0
info:
  title: Vulnerability Import API
  version: 1.0.0
  description: API contract for uploading vulnerability scan Excel files

servers:
  - url: http://localhost:8080
    description: Local development server

security:
  - bearerAuth: []

paths:
  /api/import/upload-vulnerability-xlsx:
    post:
      summary: Upload vulnerability scan Excel file
      description: |
        Import vulnerability data from an Excel file (.xlsx format).
        The file must contain columns: Hostname, Local IP, Host groups, Cloud service account ID,
        Cloud service instance ID, OS version, Active Directory domain, Vulnerability ID,
        CVSS severity, Vulnerable product versions, Days open.

        Assets will be auto-created if hostname not found. Duplicate vulnerabilities are kept
        as separate records for historical tracking.

      operationId: uploadVulnerabilityXlsx

      tags:
        - Import

      security:
        - bearerAuth: []

      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                xlsxFile:
                  type: string
                  format: binary
                  description: Excel file (.xlsx) containing vulnerability data
                scanDate:
                  type: string
                  format: date-time
                  description: ISO 8601 datetime when the scan was performed (e.g., 2025-10-03T14:30:00)
                  example: "2025-10-03T14:30:00"
              required:
                - xlsxFile
                - scanDate

      responses:
        '200':
          description: Import successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Human-readable summary message
                    example: "15 imported, 2 skipped (invalid), 3 assets created"
                  imported:
                    type: integer
                    description: Number of vulnerabilities successfully imported
                    example: 15
                  skipped:
                    type: integer
                    description: Number of rows skipped due to validation errors
                    example: 2
                  assetsCreated:
                    type: integer
                    description: Number of new assets auto-created
                    example: 3
                  skippedDetails:
                    type: array
                    description: Details of skipped rows (optional, for debugging)
                    items:
                      type: object
                      properties:
                        row:
                          type: integer
                          description: Row number (1-indexed, excluding header)
                          example: 5
                        reason:
                          type: string
                          description: Reason why row was skipped
                          example: "Missing required hostname"
                required:
                  - message
                  - imported
                  - skipped
                  - assetsCreated

        '400':
          description: Bad Request - Validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid file format. Only .xlsx files are supported"

        '401':
          description: Unauthorized - Authentication required
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized"

        '413':
          description: Payload Too Large - File exceeds size limit
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "File size exceeds maximum limit of 10MB"

        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error processing file: Unable to read Excel workbook"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from /api/auth/login
