package com.secman.service

import jakarta.inject.Singleton
import org.apache.poi.wp.usermodel.HeaderFooterType
import org.apache.poi.xwpf.usermodel.BreakType
import org.apache.poi.xwpf.usermodel.ParagraphAlignment
import org.apache.poi.xwpf.usermodel.XWPFDocument
import java.io.ByteArrayOutputStream

/**
 * Builds the example company Word template shipped with secman.
 *
 * This is the single source of truth for that document: the committed artefact under
 * `resources/templates/` is produced by this builder (see the `generateExampleRequirementTemplate`
 * Gradle task), the seeder installs that artefact as the initial ACTIVE template, and admins
 * download the same bytes to rebrand. Keeping the generator in code rather than hand-editing an
 * opaque `.docx` is what makes the shipped binary reviewable.
 *
 * The layout deliberately exercises every part of the template contract:
 *  - a cover page carrying the document title and classification,
 *  - a release metadata block (name / version / date / status), which is the point of exporting a
 *    release: the collection of requirements frozen at a moment in time,
 *  - the `${requirements}` insertion point at body level, so requirement content renders *between*
 *    the front matter and the closing section rather than being appended at the end,
 *  - a closing/approval section after the insertion point,
 *  - a header and footer carrying the classification and a page number field.
 *
 * @see RequirementExportTemplateValidationService for the rules this output must satisfy.
 */
@Singleton
class ExampleRequirementExportTemplateBuilder {

    companion object {
        /** Classpath location of the committed artefact this builder generates. */
        const val RESOURCE_PATH = "/templates/secman-company-requirements-template.docx"

        /** Filename presented on download and recorded on the seeded template row. */
        const val FILENAME = "secman-company-requirements-template.docx"

        /** Name the seeder gives the installed example. */
        const val TEMPLATE_NAME = "SecMan example company template"

        const val TEMPLATE_VERSION_LABEL = "1.0"

        const val TEMPLATE_DESCRIPTION =
            "Example company template shipped with SecMan. Rebrand it with your own cover page, " +
                "fonts, colours, header and footer, then upload it as a new template."

        /** Placeholder for the company name, left as literal text for the design team to replace. */
        private const val COMPANY_NAME = "ACME Corporation"
    }

    /**
     * The example template bytes: the committed artefact when one is on the classpath, otherwise a
     * freshly built document.
     *
     * Both paths yield the same document, because the artefact is generated by [build] in the first
     * place (`./gradlew :backendng:generateExampleRequirementTemplate`). Committing it is therefore
     * optional — useful to hand a file to a design team, never required for the feature to work,
     * and the fallback is what keeps builder and shipped bytes from drifting apart.
     */
    fun loadOrBuild(): ByteArray =
        javaClass.getResourceAsStream(RESOURCE_PATH)?.use { it.readBytes() } ?: build()

    /** Renders the example template to a `.docx` byte array. */
    fun build(): ByteArray {
        XWPFDocument().use { document ->
            WordExportStyle.setStandardMargins(document)
            buildHeaderAndFooter(document)
            buildCoverPage(document)
            buildReleaseMetadataBlock(document)
            buildIntroduction(document)
            buildRequirementsInsertionPoint(document)
            buildClosingSection(document)

            ByteArrayOutputStream().use { out ->
                document.write(out)
                return out.toByteArray()
            }
        }
    }

    private fun buildHeaderAndFooter(document: XWPFDocument) {
        val header = document.createHeader(HeaderFooterType.DEFAULT)
        val headerParagraph = header.createParagraph()
        headerParagraph.alignment = ParagraphAlignment.RIGHT
        WordExportStyle.run(
            headerParagraph, "$COMPANY_NAME  |  \${classification}",
            size = WordExportStyle.SIZE_META, color = WordExportStyle.COLOR_SECONDARY
        )

        val footer = document.createFooter(HeaderFooterType.DEFAULT)
        val footerParagraph = footer.createParagraph()
        footerParagraph.alignment = ParagraphAlignment.CENTER
        // Page numbering is deliberately left out: a PAGE field is one click to add in Word when
        // rebranding, and hand-writing the field-code XML here would couple this builder to schema
        // classes that the trimmed poi-ooxml-lite jar does not guarantee.
        WordExportStyle.run(
            footerParagraph, "\${documentTitle}  |  Exported \${exportDate} by \${exportedBy}",
            size = WordExportStyle.SIZE_META, color = WordExportStyle.COLOR_SECONDARY
        )
    }

    private fun buildCoverPage(document: XWPFDocument) {
        val spacer = document.createParagraph()
        spacer.createRun().addBreak()

        val kicker = document.createParagraph()
        kicker.alignment = ParagraphAlignment.CENTER
        WordExportStyle.run(
            kicker, COMPANY_NAME.uppercase(),
            size = WordExportStyle.SIZE_KICKER, bold = true, color = WordExportStyle.COLOR_ACCENT
        )

        val logoHint = document.createParagraph()
        logoHint.alignment = ParagraphAlignment.CENTER
        WordExportStyle.run(
            logoHint, "[ Replace this line with your company logo ]",
            size = 9, italic = true, color = WordExportStyle.COLOR_SECONDARY
        )

        document.createParagraph()

        val title = document.createParagraph()
        title.alignment = ParagraphAlignment.CENTER
        title.spacingAfter = 120
        WordExportStyle.run(title, "\${documentTitle}", size = WordExportStyle.SIZE_DOCUMENT_TITLE, bold = true)

        val classification = document.createParagraph()
        classification.alignment = ParagraphAlignment.CENTER
        WordExportStyle.run(
            classification, "Classification: \${classification}",
            size = 11, bold = true, color = WordExportStyle.COLOR_CLASSIFICATION
        )

        val counts = document.createParagraph()
        counts.alignment = ParagraphAlignment.CENTER
        WordExportStyle.run(
            counts, "\${requirementCount} requirements  |  Language: \${language}",
            color = WordExportStyle.COLOR_SECONDARY
        )
    }

    /**
     * The release block. `${releaseName}`, `${releaseVersion}`, `${releaseDate}` and
     * `${releaseStatus}` all resolve to an empty string when the export is not pinned to a release,
     * so the same template serves both a frozen release and a live "all requirements" export.
     */
    private fun buildReleaseMetadataBlock(document: XWPFDocument) {
        document.createParagraph()

        val heading = document.createParagraph()
        heading.alignment = ParagraphAlignment.CENTER
        WordExportStyle.run(heading, "Requirements release", size = 12, bold = true)

        val table = document.createTable(4, 2)
        table.setWidth("60%")
        WordExportStyle.applyHairlineBorders(table)

        val rows = listOf(
            "Release name" to "\${releaseName}",
            "Version" to "\${releaseVersion}",
            "Release date" to "\${releaseDate}",
            "Status" to "\${releaseStatus}"
        )
        rows.forEachIndexed { index, (label, placeholder) ->
            val row = table.getRow(index)
            WordExportStyle.run(row.getCell(0).paragraphs.first(), label, bold = true)
            WordExportStyle.run(row.getCell(1).paragraphs.first(), placeholder)
        }

        val description = document.createParagraph()
        WordExportStyle.run(description, "\${releaseDescription}", italic = true, color = WordExportStyle.COLOR_SECONDARY)

        document.createParagraph().createRun().addBreak(BreakType.PAGE)
    }

    private fun buildIntroduction(document: XWPFDocument) {
        WordExportStyle.sectionHeading(document, "1. Purpose and scope")

        val body = document.createParagraph()
        WordExportStyle.run(
            body,
            "This document lists the security requirements that apply to systems operated by " +
                "$COMPANY_NAME. Replace this introduction with your own scope, applicability and " +
                "review statements. Everything before the requirements section is yours to design; " +
                "SecMan only substitutes the \${...} placeholders and renders the requirement body."
        )

        val useCaseNote = document.createParagraph()
        WordExportStyle.run(useCaseNote, "Use case in scope: \${useCaseName}", italic = true, color = WordExportStyle.COLOR_SECONDARY)

        document.createParagraph()
    }

    /**
     * The insertion point.
     *
     * It must sit in its own top-level paragraph — not in a table cell, header or footer — because
     * requirement content is inserted as body-level paragraphs in its place. The validation service
     * enforces exactly that.
     */
    private fun buildRequirementsInsertionPoint(document: XWPFDocument) {
        WordExportStyle.sectionHeading(document, "2. Requirements")

        val marker = document.createParagraph()
        marker.createRun().setText("\${requirements}")
    }

    private fun buildClosingSection(document: XWPFDocument) {
        document.createParagraph().createRun().addBreak(BreakType.PAGE)

        WordExportStyle.sectionHeading(document, "3. Approval")

        val body = document.createParagraph()
        WordExportStyle.run(
            body,
            "This section is rendered after the requirements, which is what the \${requirements} " +
                "insertion point is for. Use it for sign-off, revision history or an appendix."
        )

        document.createParagraph()

        val approvalTable = document.createTable(2, 3)
        approvalTable.setWidth("100%")
        WordExportStyle.applyHairlineBorders(approvalTable)
        listOf("Role", "Name", "Date").forEachIndexed { column, label ->
            WordExportStyle.run(approvalTable.getRow(0).getCell(column).paragraphs.first(), label, bold = true)
        }
        WordExportStyle.shadeHeaderRow(approvalTable)
        listOf("Document owner", "", "").forEachIndexed { column, value ->
            WordExportStyle.run(approvalTable.getRow(1).getCell(column).paragraphs.first(), value)
        }
    }
}
