package com.secman.service

import jakarta.inject.Singleton
import org.apache.poi.wp.usermodel.HeaderFooterType
import org.apache.poi.xwpf.usermodel.BreakType
import org.apache.poi.xwpf.usermodel.ParagraphAlignment
import org.apache.poi.xwpf.usermodel.XWPFDocument
import java.io.ByteArrayOutputStream

/**
 * Builds the example company Word template shipped with secman.
 *
 * This is the single source of truth for that document: the committed artefact under
 * `resources/templates/` is produced by this builder (see the `generateExampleRequirementTemplate`
 * Gradle task), the seeder installs that artefact as the initial ACTIVE template, and admins
 * download the same bytes to rebrand. Keeping the generator in code rather than hand-editing an
 * opaque `.docx` is what makes the shipped binary reviewable.
 *
 * The layout deliberately exercises every part of the template contract:
 *  - a cover page carrying the document title and classification,
 *  - a release metadata block (name / version / date / status), which is the point of exporting a
 *    release: the collection of requirements frozen at a moment in time,
 *  - the `${requirements}` insertion point at body level, so requirement content renders *between*
 *    the front matter and the closing section rather than being appended at the end,
 *  - a closing/approval section after the insertion point,
 *  - a header and footer carrying the classification and a page number field.
 *
 * @see RequirementExportTemplateValidationService for the rules this output must satisfy.
 */
@Singleton
class ExampleRequirementExportTemplateBuilder {

    companion object {
        /** Classpath location of the committed artefact this builder generates. */
        const val RESOURCE_PATH = "/templates/secman-company-requirements-template.docx"

        /** Filename presented on download and recorded on the seeded template row. */
        const val FILENAME = "secman-company-requirements-template.docx"

        /** Name the seeder gives the installed example. */
        const val TEMPLATE_NAME = "SecMan example company template"

        const val TEMPLATE_VERSION_LABEL = "1.0"

        const val TEMPLATE_DESCRIPTION =
            "Example company template shipped with SecMan. Rebrand it with your own cover page, " +
                "fonts, colours, header and footer, then upload it as a new template."

        /** Placeholder for the company name, left as literal text for the design team to replace. */
        private const val COMPANY_NAME = "ACME Corporation"
    }

    /**
     * The example template bytes: the committed artefact when one is on the classpath, otherwise a
     * freshly built document.
     *
     * Both paths yield the same document, because the artefact is generated by [build] in the first
     * place (`./gradlew :backendng:generateExampleRequirementTemplate`). Committing it is therefore
     * optional — useful to hand a file to a design team, never required for the feature to work,
     * and the fallback is what keeps builder and shipped bytes from drifting apart.
     */
    fun loadOrBuild(): ByteArray =
        javaClass.getResourceAsStream(RESOURCE_PATH)?.use { it.readBytes() } ?: build()

    /** Renders the example template to a `.docx` byte array. */
    fun build(): ByteArray {
        XWPFDocument().use { document ->
            buildHeaderAndFooter(document)
            buildCoverPage(document)
            buildReleaseMetadataBlock(document)
            buildIntroduction(document)
            buildRequirementsInsertionPoint(document)
            buildClosingSection(document)

            ByteArrayOutputStream().use { out ->
                document.write(out)
                return out.toByteArray()
            }
        }
    }

    private fun buildHeaderAndFooter(document: XWPFDocument) {
        val header = document.createHeader(HeaderFooterType.DEFAULT)
        val headerParagraph = header.createParagraph()
        headerParagraph.alignment = ParagraphAlignment.RIGHT
        headerParagraph.createRun().apply {
            setText("$COMPANY_NAME  |  \${classification}")
            fontSize = 8
            color = "808080"
        }

        val footer = document.createFooter(HeaderFooterType.DEFAULT)
        val footerParagraph = footer.createParagraph()
        footerParagraph.alignment = ParagraphAlignment.CENTER
        // Page numbering is deliberately left out: a PAGE field is one click to add in Word when
        // rebranding, and hand-writing the field-code XML here would couple this builder to schema
        // classes that the trimmed poi-ooxml-lite jar does not guarantee.
        footerParagraph.createRun().apply {
            setText("\${documentTitle}  |  Exported \${exportDate} by \${exportedBy}")
            fontSize = 8
            color = "808080"
        }
    }

    private fun buildCoverPage(document: XWPFDocument) {
        val spacer = document.createParagraph()
        spacer.createRun().addBreak()

        val company = document.createParagraph()
        company.alignment = ParagraphAlignment.CENTER
        company.createRun().apply {
            setText(COMPANY_NAME)
            fontSize = 14
            isBold = true
            color = "1F4E79"
        }

        val logoHint = document.createParagraph()
        logoHint.alignment = ParagraphAlignment.CENTER
        logoHint.createRun().apply {
            setText("[ Replace this line with your company logo ]")
            fontSize = 9
            isItalic = true
            color = "A0A0A0"
        }

        document.createParagraph()

        val title = document.createParagraph()
        title.alignment = ParagraphAlignment.CENTER
        title.createRun().apply {
            setText("\${documentTitle}")
            fontSize = 26
            isBold = true
            color = "1F4E79"
        }

        val classification = document.createParagraph()
        classification.alignment = ParagraphAlignment.CENTER
        classification.createRun().apply {
            setText("Classification: \${classification}")
            fontSize = 11
            isBold = true
            color = "C00000"
        }

        val counts = document.createParagraph()
        counts.alignment = ParagraphAlignment.CENTER
        counts.createRun().apply {
            setText("\${requirementCount} requirements  |  Language: \${language}")
            fontSize = 10
            color = "606060"
        }
    }

    /**
     * The release block. `${releaseName}`, `${releaseVersion}`, `${releaseDate}` and
     * `${releaseStatus}` all resolve to an empty string when the export is not pinned to a release,
     * so the same template serves both a frozen release and a live "all requirements" export.
     */
    private fun buildReleaseMetadataBlock(document: XWPFDocument) {
        document.createParagraph()

        val heading = document.createParagraph()
        heading.alignment = ParagraphAlignment.CENTER
        heading.createRun().apply {
            setText("Requirements release")
            fontSize = 12
            isBold = true
        }

        val table = document.createTable(4, 2)
        table.setWidth("60%")

        val rows = listOf(
            "Release name" to "\${releaseName}",
            "Version" to "\${releaseVersion}",
            "Release date" to "\${releaseDate}",
            "Status" to "\${releaseStatus}"
        )
        rows.forEachIndexed { index, (label, placeholder) ->
            val row = table.getRow(index)
            row.getCell(0).paragraphs.first().createRun().apply {
                setText(label)
                isBold = true
                fontSize = 10
            }
            row.getCell(1).paragraphs.first().createRun().apply {
                setText(placeholder)
                fontSize = 10
            }
        }

        val description = document.createParagraph()
        description.createRun().apply {
            setText("\${releaseDescription}")
            fontSize = 10
            isItalic = true
        }

        document.createParagraph().createRun().addBreak(BreakType.PAGE)
    }

    private fun buildIntroduction(document: XWPFDocument) {
        val heading = document.createParagraph()
        heading.style = "Heading1"
        heading.createRun().apply {
            setText("1. Purpose and scope")
            fontSize = 16
            isBold = true
        }

        val body = document.createParagraph()
        body.createRun().setText(
            "This document lists the security requirements that apply to systems operated by " +
                "$COMPANY_NAME. Replace this introduction with your own scope, applicability and " +
                "review statements. Everything before the requirements section is yours to design; " +
                "SecMan only substitutes the \${...} placeholders and renders the requirement body."
        )

        val useCaseNote = document.createParagraph()
        useCaseNote.createRun().apply {
            setText("Use case in scope: \${useCaseName}")
            fontSize = 10
            isItalic = true
        }

        document.createParagraph()
    }

    /**
     * The insertion point.
     *
     * It must sit in its own top-level paragraph — not in a table cell, header or footer — because
     * requirement content is inserted as body-level paragraphs in its place. The validation service
     * enforces exactly that.
     */
    private fun buildRequirementsInsertionPoint(document: XWPFDocument) {
        val heading = document.createParagraph()
        heading.style = "Heading1"
        heading.createRun().apply {
            setText("2. Requirements")
            fontSize = 16
            isBold = true
        }

        val marker = document.createParagraph()
        marker.createRun().setText("\${requirements}")
    }

    private fun buildClosingSection(document: XWPFDocument) {
        document.createParagraph().createRun().addBreak(BreakType.PAGE)

        val heading = document.createParagraph()
        heading.style = "Heading1"
        heading.createRun().apply {
            setText("3. Approval")
            fontSize = 16
            isBold = true
        }

        val body = document.createParagraph()
        body.createRun().setText(
            "This section is rendered after the requirements, which is what the \${requirements} " +
                "insertion point is for. Use it for sign-off, revision history or an appendix."
        )

        document.createParagraph()

        val approvalTable = document.createTable(2, 3)
        approvalTable.setWidth("100%")
        listOf("Role", "Name", "Date").forEachIndexed { column, label ->
            approvalTable.getRow(0).getCell(column).paragraphs.first().createRun().apply {
                setText(label)
                isBold = true
                fontSize = 10
            }
        }
        listOf("Document owner", "", "").forEachIndexed { column, value ->
            approvalTable.getRow(1).getCell(column).paragraphs.first().createRun().apply {
                setText(value)
                fontSize = 10
            }
        }
    }
}
