#!/bin/bash
# secman - CLI wrapper for secman security management tool

export MICRONAUT_ENVIRONMENTS=dev
export SECMAN_BACKEND_URL="pass://Test/SECMAN/SECMAN_BACKEND_BASE_URL"
export DB_CONNECT="pass://Test/SECMAN/DB_CONNECT"
export SECMAN_DEBUG=true

export FALCON_CLIENT_ID="pass://Test/SECMAN/FALCON_CLIENT_ID"
export FALCON_CLIENT_SECRET="pass://Test/SECMAN/FALCON_CLIENT_SECRET"
export FALCON_CLOUD_REGION="pass://Test/SECMAN/FALCON_CLOUD_REGION"
export SECMAN_OPENROUTER_API_KEY="pass://Test/SECMAN/OPENROUTER_API_KEY"
export SECMAN_ADMIN_NAME="pass://Test/SECMAN/SECMAN_ADMIN_NAME"
export SECMAN_ADMIN_PASS="pass://Test/SECMAN/SECMAN_ADMIN_PASS"
export API_KEY="pass://Test/SECMAN/MCP_API_KEY"
export SECMAN_ADMIN_EMAIL="pass://Test/SECMAN/SECMAN_ADMIN_EMAIL"
export AWS_ACCESS_KEY_ID="pass://Test/SECMAN/SECMAN_AWS_ACCESS_KEY_ID"
export AWS_SECRET_ACCESS_KEY="pass://Test/SECMAN/SECMAN_AWS_SECRET_ACCESS_KEY"
export AWS_SESSION_TOKEN="pass://Test/SECMAN/SECMAN_AWS_ACCESS_TOKEN"
export SECMAN_BACKEND_URL="pass://Test/SECMAN/SECMAN_BACKEND_BASE_URL"
export SECMAN_INSECURE="pass://Test/SECMAN/SECMAN_SSL_ACCEPT_ALL"



export JWT_SECRET=$(openssl rand -base64 48)

pass-cli run -- ./scriptpp/e2e-test.2.sh
