version: '3.8'

services:
  database:
    build:
      context: ../database
      dockerfile: Dockerfile
    container_name: secman-db-dev
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root123}
      - MYSQL_DATABASE=secman
      - MYSQL_USER=secman
      - MYSQL_PASSWORD=${DB_PASSWORD:-CHANGEME}
    volumes:
      - secman_db_dev_data:/var/lib/mysql
      - ../database/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "${DB_PORT:-3307}:3306"  # Different port for dev to avoid conflicts
    networks:
      - secman-dev-network
    restart: unless-stopped

  backend:
    build:
      context: ../..
      dockerfile: docker/backend/Dockerfile
    container_name: secman-backend-dev
    environment:
      - MICRONAUT_ENVIRONMENTS=development,docker
      - DB_USERNAME=secman
      - DB_PASSWORD=${DB_PASSWORD:-CHANGEME}
      - JWT_SECRET=${JWT_SECRET:-pleasechangethissecrectokeyproductionforsecurityreasonsmustbe256bits}
      - DATASOURCES_DEFAULT_URL=jdbc:mariadb://database:3306/secman
    volumes:
      - ../../src/backendng:/app/src:ro  # Mount source for hot reload
    ports:
      - "${BACKEND_PORT:-8081}:8080"  # Different port for dev
    networks:
      - secman-dev-network
    depends_on:
      - database
    restart: unless-stopped
    command: ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]

  frontend:
    build:
      context: ../..
      dockerfile: docker/frontend/Dockerfile
      target: development
    container_name: secman-frontend-dev
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://backend:8080
    volumes:
      - ../../src/frontend:/app:rw  # Mount source for hot reload
      - /app/node_modules  # Exclude node_modules from mount
    ports:
      - "${FRONTEND_PORT:-4322}:4321"  # Different port for dev
    networks:
      - secman-dev-network
    depends_on:
      - backend
    restart: unless-stopped
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

volumes:
  secman_db_dev_data:
    driver: local

networks:
  secman-dev-network:
    driver: bridge